[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "/src/pages/api/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  functionsPort = 8888

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200